"""Created necessary tables

Revision ID: 802ece991aaf
Revises: 
Create Date: 2025-07-05 15:50:59.921965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802ece991aaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('komen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('date_commented', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('komen')
    # ### end Alembic commands ###
